matrix:
- name: python
  sources:
  - '**/*.py'
  ignores:
  - '.venv/**'
  - '__pycache__/**'
  - '.jj/**'
  - 'build/**'
  - 'dist/**'
  hunspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .project-words.txt
    output: build/dictionary/python.dic
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
      decode_escapes: true

- name: markdown
  sources:
  - README.md
  ignores:
  - '.venv/**'
  - '__pycache__/**'
  - '.jj/**'
  aspell:
    lang: en
    d: en_US
    mode: markdown
  dictionary:
    wordlists:
    - .project-words.txt
    output: build/dictionary/markdown.dic
  pipeline:
  - pyspelling.filters.markdown
