matrix:
- name: python
  sources:
  - '**/*.py'
  ignores:
  - '.venv/**'
  - '__pycache__/**'
  - '.jj/**'
  - 'build/**'
  - 'dist/**'
  hunspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .project-words.txt
    output: build/dictionary/python.dic
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
      decode_escapes: true
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore code blocks in docstrings
      - open: '(?s)^(?P<open> *```.*?)$'
        close: '^(?P=open)$'
      # Ignore URLs
      - open: '\b(?:https?|ftp)://'
        close: '(?=\s|$)'
      # Ignore file paths
      - open: '(?i)(?:(?:[a-z]:)?[/\\])?(?:[a-z0-9_.-]+[/\\])+[a-z0-9_.-]*'
        close: '(?=\s|$)'
  - pyspelling.filters.url

- name: markdown
  sources:
  - '**/*.md'
  ignores:
  - '.venv/**'
  - '__pycache__/**'
  - '.jj/**'
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .project-words.txt
    output: build/dictionary/markdown.dic
  pipeline:
  - pyspelling.filters.markdown
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore code blocks
      - open: '(?s)^```.*?$'
        close: '^```$'
      # Ignore inline code
      - open: '`'
        close: '`'
      # Ignore URLs
      - open: '\b(?:https?|ftp)://'
        close: '(?=\s|$)'
  - pyspelling.filters.url
